First draft for bot documentation
asadm/playroom-docs pull request #14
Opened 2023-09-22 02:03 UTC by junaidzaidi

Added Documentation for Custom Bot, DQN Bot, DQN Bot with Joystick
Updated InsertCoin with parameters like 'enableBots' and 'botOptions'

2023-09-22 04:38 UTC, asadm requested changes

2023-09-22 04:38 UTC, asadm commented on pages/bots/dqnbot.mdx
> +# DQN Bot Integration with Playroom
can you move dqn and dqnjoystick in a separate PR. Let's first launch custom / basic bot only.

2023-09-22 05:59 UTC, junaidzaidi commented on pages/bots/custombot.mdx
> +    // Logic to make the bot act within the game loop
Resolved in seperate PR

2023-09-22 06:00 UTC, junaidzaidi commented on pages/bots/custombot.mdx
> +      ... YourCustomBot parameters,
Resolved in separate PR

2023-09-22 06:00 UTC, junaidzaidi commented on pages/bots/custombot.mdx
> +is to ascertain that your custom bot is identified as a Bot type within the SDK.
Resolved in separate PR

2023-09-22 06:01 UTC, junaidzaidi commented on pages/bots/custombot.mdx
> +}
Resolved in separate PR

2024-06-24 02:15 UTC, Acorn-Studios commented
Does this need to be updated and pushed for the latest docs version or are we just leaving it?

2026-09-23 14:55 UTC, closed without merging